### ISSUE TITLE
Root issue

### ISSUE THREAD

**Issue by Antoine-O** [CyCoreSystems/docker-meteor#34]
Hello, 

As said here : http://stackoverflow.com/questions/40253443/you-have-run-meteor-as-root-when-building-meteor-app-in-docker

There is now a problem with using root user for deployment. 

According to the suggestion an account should created for this specific purpose.

Did you already find a solution ?

**Comment by Ulexus** [comment]
I hadn't yet noticed, no.  It is easy enough to resolve, I think.  I've been meaning to migrate to an unprivileged user for a while anyway.

PRs definitely welcome, though.

**Comment by Antoine-O** [comment]
Id love to but this is beyond my knowledge right now :/

**Comment by Ulexus** [comment]
Fixed by #35

**Comment by Antoine-O** [comment]
well done guys. I had to make some changes with permission as I uses source code as input and no bundles. but it works ! thanks !

**Comment by Ulexus** [comment]
@Antoine-O Yeah, the permissions-of-the-source issue was what made my original solution so complicated.  I liked @dorandeluz much better because it was massively simpler, more elegant, and it's easy enough to just request people to change the permissions on their source.  If you use the git- or URL-based sourcing, it's not an issue.
