### ISSUE TITLE
Deploy with token

### ISSUE THREAD

**Issue by nicolaslopezj** [CyCoreSystems/docker-meteor#5]
How can I deploy with a github api access token?
Is there a option to specify the github username? If there is, we could set the access token to the username and it will work.

**Comment by Ulexus** [comment]
As per the README:
Deploy-key support (set DEPLOY_KEY to the location of your SSH key file)

You needn't specify a username.

**Comment by nicolaslopezj** [comment]
But in this case I'm not talking about ssh keys. I have a GitHub app, and some repos that I want to deploy are private. I have the api token, which is not the same as a ssh key

**Comment by Ulexus** [comment]
Are you talking about your Meteor app using a Github API key?  In that case, you'll need to bundle the key in with your app or your database (beware of the security implications of doing so, of course).  You could also set an environment variable with it and reference that from within Meteor.

I don't see, otherwise, what a Github API key has to do with Meteor deployment.  If your Meteor app is on Github, you can use a deploy key (SSH) for it.
